base: base-mixed.yaml
name: BEVNet-no_attn-mixed
notes: a configuration for BEVNet without head height attention
train_setting:
    train_routines:
        -   epochs: 5
            init_lr:
            train_modules:
                - decoder_bev
            use_inferred_pose: false
        -   epochs: 50
            init_lr:
            train_modules:
                - decoder_bev
            use_inferred_pose: true
        -   epochs: 100
            init_lr:
            train_modules:
                - encoder.encoder_feet
                - encoder.encoder_head
                - decoder_feet
                - decoder_head
                - decoder_bev
            use_inferred_pose: true
        -   epochs: 150
            init_lr:
            train_modules:
                - encoder.encoder_feet
                - encoder.encoder_head
                - decoder_feet
                - decoder_head
                - decoder_pose
                - decoder_bev
            use_inferred_pose: true
        -   epochs: 200
            init_lr:
            train_modules:
                - encoder
                - decoder_feet
                - decoder_head
                - decoder_pose
                - decoder_bev
            use_inferred_pose: true
model:
    name: BEVNetNoAttention
    kwargs:
        bev_decoder_option:
            head_heights: null
