base: base-mixed-kitti.yaml
name: BEVNet-all-mixed-kitti
notes: a configuration for BEVNet with all branches enabled
train_setting:
    train_routines:
        -   epochs: 5
            init_lr:
            train_modules:
                - decoder_bev
                - head_height_attention
            use_inferred_pose: false
        -   epochs: 50
            init_lr:
            train_modules:
                - decoder_bev
                - head_height_attention
            use_inferred_pose: true
        -   epochs: 100
            init_lr:
            train_modules:
                - encoder.encoder_feet
                - encoder.encoder_head
                - decoder_feet
                - decoder_head
                - decoder_bev
                - head_height_attention
            use_inferred_pose: true
        -   epochs: 150
            init_lr:
            train_modules:
                - encoder.encoder_feet
                - encoder.encoder_head
                - decoder_feet
                - decoder_head
                - decoder_pose
                - decoder_bev
                - head_height_attention
            use_inferred_pose: true
        -   epochs: 200
            init_lr:
            train_modules:
                - encoder
                - decoder_feet
                - decoder_head
                - decoder_pose
                - decoder_bev
                - head_height_attention
            use_inferred_pose: true
