_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
    WEIGHTS: checkpoints/faster_rcnn_r_50_fpn_3x/model_final_280758.pkl
    MASK_ON: False
    RESNETS:
        DEPTH: 50
    ROI_HEADS:
        NUM_CLASSES: 1
SOLVER:
    STEPS: (210000, 250000)
    MAX_ITER: 5000
